source 'https://github.com/CocoaPods/Specs.git'
source 'http://gitlab.jucaicat.net/iOS-Framework/Specs.git'
platform :ios, '7.0'

inhibit_all_warnings!

target :'WJCacheKeychain-example' do

pod 'WJCacheAPI'
pod 'UICKeyChainStore', '2.1.0'

end
